"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Lead } from "@/lib/types";
const initial = { name: "", email: "", company: "", description: "", budget: "", timeline: "" };
type Form = typeof initial;
export default function Home() {
 const [form,setForm]=useState<Form>(initial), [leads,setLeads]=useState<Lead[]>([]), [loading,setLoading]=useState(false), [notice,setNotice]=useState(""), [tab,setTab]=useState<"dashboard"|"new">("dashboard");
 const refresh=async()=>{const r=await fetch("/api/leads"); if(r.ok) setLeads((await r.json()).leads)};
 useEffect(()=>{refresh()},[]); const stats=useMemo(()=>({total:leads.length, hot:leads.filter(l=>l.priority==="High").length, automated:leads.filter(l=>l.automationTriggered).length, avg:leads.length?Math.round(leads.reduce((s,l)=>s+l.score,0)/leads.length):0}),[leads]);
 const update=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setNotice("");try {const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.message);setNotice(`✓ ${data.message} Score: ${data.insight.score}/100 · ${data.insight.priority} priority.`);setForm(initial);await refresh();setTab("dashboard")}catch(e){setNotice(e instanceof Error?e.message:"Could not submit lead.")}finally{setLoading(false)}}
 return <main><nav><div className="brand"><span>✦</span> LeadFlow <b>AI</b></div><div className="navlinks"><button className={tab==="dashboard"?"active":""} onClick={()=>setTab("dashboard")}>Dashboard</button><button className={tab==="new"?"active":""} onClick={()=>setTab("new")}>New lead</button><a href="#how">How it works</a></div><div className="mode"><i/> Free local-first</div></nav>
 <section className="hero"><div><p className="eyebrow">AI SALES AUTOMATION • PORTFOLIO PROJECT</p><h1>Turn enquiries into <em>qualified</em> opportunities.</h1><p className="intro">A polished, zero-cost lead intake system that scores, summarizes, and routes every prospect to n8n — without paid AI APIs.</p><button className="primary" onClick={()=>setTab("new")}>Capture a lead <span>→</span></button></div><div className="orb"><div className="signal">AI<br/><small>analysis</small></div><div className="float one">⚡ New lead</div><div className="float two">98 <small>score</small></div></div></section>
 {notice&&<div className="notice">{notice}</div>}
 {tab==="dashboard"?<section className="workspace"><div className="sectionhead"><div><p className="eyebrow">OVERVIEW</p><h2>Lead command center</h2></div><button className="ghost" onClick={()=>setTab("new")}>+ Add lead</button></div><div className="stats"><Stat label="Total leads" value={stats.total} accent="violet"/><Stat label="High-intent" value={stats.hot} accent="pink"/><Stat label="Automated" value={stats.automated} accent="cyan"/><Stat label="Average score" value={`${stats.avg}%`} accent="lime"/></div><div className="tablecard"><div className="tablehead"><h3>Recent opportunities</h3><span>{leads.length} records</span></div>{leads.length===0?<div className="empty"><strong>Your pipeline is ready.</strong><br/>Capture a demo lead to see AI qualification in action.</div>:<div className="leadlist">{leads.map(l=><article className="lead" key={l.id}><div className="avatar">{l.name.slice(0,1)}</div><div className="identity"><strong>{l.name}</strong><span>{l.company} · {l.email}</span></div><div><span className="tag">{l.category}</span></div><div className="score"><b>{l.score}</b><span>AI score</span></div><div><span className={`priority ${l.priority.toLowerCase()}`}>{l.priority}</span></div><div className="automation">{l.automationTriggered?"● n8n sent":"● Demo mode"}</div></article>)}</div>}</div></section>:<section className="formwrap"><div className="formintro"><p className="eyebrow">LEAD INTAKE</p><h2>Start a conversation worth having.</h2><p>Every submission is stored locally, analyzed with transparent rules, and optionally posted to your n8n webhook.</p><div className="steps"><span>01 Capture</span><span>02 Qualify</span><span>03 Automate</span></div></div><form onSubmit={submit}><div className="formgrid"><Field label="Full name" value={form.name} onChange={v=>update("name",v)} placeholder="Ayesha Rahman" required/><Field label="Work email" value={form.email} onChange={v=>update("email",v)} placeholder="ayesha@company.com" type="email" required/><Field label="Company" value={form.company} onChange={v=>update("company",v)} placeholder="Northstar Studio" required/><Field label="Estimated budget" value={form.budget} onChange={v=>update("budget",v)} placeholder="$5,000 – $10,000"/></div><label>Project details <sup>*</sup><textarea required value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Tell us what you want to build, the problem it solves, and the desired outcome..." rows={5}/></label><Field label="Ideal timeline" value={form.timeline} onChange={v=>update("timeline",v)} placeholder="Within 4 weeks"/><button className="primary submit" disabled={loading}>{loading?"Analyzing lead…":"Analyze & send lead →"}</button><p className="fineprint">No paid AI services. Your data stays on your machine in local development.</p></form></section>}
 <section id="how" className="how"><p className="eyebrow">BUILT TO EXPLAIN ITSELF</p><h2>One flow. Useful proof.</h2><div className="flow"><div><b>01</b><strong>Capture</strong><span>Modern web form validates and stores each lead.</span></div><i>→</i><div><b>02</b><strong>Qualify</strong><span>Local AI-style scoring generates a category and follow-up.</span></div><i>→</i><div><b>03</b><strong>Automate</strong><span>n8n receives a webhook and triggers your workflow.</span></div></div></section><footer>LeadFlow AI · Built with Next.js, SQLite & n8n · <span>Free-tier friendly</span></footer></main>}
function Stat({label,value,accent}:{label:string,value:string|number,accent:string}){return <div className={`stat ${accent}`}><span>{label}</span><b>{value}</b><small>Live from your pipeline</small></div>}
function Field({label,value,onChange,placeholder,required,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;required?:boolean;type?:string}){return <label>{label} {required&&<sup>*</sup>}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
