import Database from "better-sqlite3";
import fs from "fs";
import path from "path";
import { neon } from "@neondatabase/serverless";
import type { Lead } from "./types";

export type NewLead = { name: string; email: string; company: string; description: string; budget: string; timeline: string; source: string; score: number; category: string; priority: string; summary: string; followUp: string; status: string; createdAt: string };
export type QualificationUpdate = { category: string; score: number; summary: string; reason: string; recommendedAction: string; source: string };
const columns = `name TEXT NOT NULL, email TEXT NOT NULL, company TEXT NOT NULL, description TEXT NOT NULL, budget TEXT DEFAULT '', timeline TEXT DEFAULT '', source TEXT DEFAULT 'Website', score INTEGER NOT NULL, category TEXT NOT NULL, priority TEXT NOT NULL, summary TEXT NOT NULL, follow_up TEXT NOT NULL, status TEXT DEFAULT 'new', automation_triggered INTEGER DEFAULT 0, ai_reason TEXT DEFAULT '', ai_recommended_action TEXT DEFAULT '', ai_qualified_at TEXT, qualification_source TEXT, created_at TEXT NOT NULL`;
const sqliteSchema = `CREATE TABLE IF NOT EXISTS leads (id INTEGER PRIMARY KEY AUTOINCREMENT, ${columns})`;
const postgresSchema = `CREATE TABLE IF NOT EXISTS leads (id BIGSERIAL PRIMARY KEY, ${columns})`;
const select = `SELECT id,name,email,company,description,budget,timeline,source,score,category,priority,summary,follow_up as "followUp",status,automation_triggered as "automationTriggered",ai_reason as "aiReason",ai_recommended_action as "aiRecommendedAction",ai_qualified_at as "aiQualifiedAt",qualification_source as "qualificationSource",created_at as "createdAt" FROM leads`;
const databaseUrl = process.env.DATABASE_URL;
let localDb: Database.Database | undefined;
let neonReady: Promise<void> | undefined;
function local() { if (!localDb) { const directory = path.join(process.cwd(), "data"); if (!fs.existsSync(directory)) fs.mkdirSync(directory, { recursive: true }); localDb = new Database(path.join(directory, "leadflow.db")); localDb.pragma("journal_mode = WAL"); localDb.exec(sqliteSchema); const localColumns = new Set((localDb.prepare("PRAGMA table_info(leads)").all() as Array<{ name: string }>).map((c) => c.name)); for (const [name, sql] of [["ai_reason", "ALTER TABLE leads ADD COLUMN ai_reason TEXT DEFAULT ''"], ["ai_recommended_action", "ALTER TABLE leads ADD COLUMN ai_recommended_action TEXT DEFAULT ''"], ["ai_qualified_at", "ALTER TABLE leads ADD COLUMN ai_qualified_at TEXT"], ["qualification_source", "ALTER TABLE leads ADD COLUMN qualification_source TEXT"]] as const) if (!localColumns.has(name)) localDb.exec(sql); } return localDb; }
async function sql() { if (!databaseUrl) return null; const client = neon(databaseUrl); neonReady ??= client.query(postgresSchema).then(() => undefined); await neonReady; return client; }
export async function listLeads(): Promise<Lead[]> { const client = await sql(); return client ? await client.query(`${select} ORDER BY id DESC`) as Lead[] : local().prepare(`${select} ORDER BY id DESC`).all() as Lead[]; }
export async function getLead(id: number): Promise<Lead | undefined> { const client = await sql(); if (client) return (await client.query(`${select} WHERE id = $1`, [id]))[0] as Lead | undefined; return local().prepare(`${select} WHERE id = ?`).get(id) as Lead | undefined; }
export async function createLead(lead: NewLead): Promise<number> { const client = await sql(); if (client) { const rows = await client.query(`INSERT INTO leads (name,email,company,description,budget,timeline,source,score,category,priority,summary,follow_up,status,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id`, [lead.name,lead.email,lead.company,lead.description,lead.budget,lead.timeline,lead.source,lead.score,lead.category,lead.priority,lead.summary,lead.followUp,lead.status,lead.createdAt]); return Number(rows[0].id); } const result = local().prepare("INSERT INTO leads (name,email,company,description,budget,timeline,source,score,category,priority,summary,follow_up,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(lead.name,lead.email,lead.company,lead.description,lead.budget,lead.timeline,lead.source,lead.score,lead.category,lead.priority,lead.summary,lead.followUp,lead.status,lead.createdAt); return Number(result.lastInsertRowid); }
export async function markAutomationTriggered(id: number) { const client = await sql(); if (client) await client.query("UPDATE leads SET automation_triggered = 1 WHERE id = $1", [id]); else local().prepare("UPDATE leads SET automation_triggered = 1 WHERE id = ?").run(id); }
export async function saveQualification(id: number, update: QualificationUpdate): Promise<boolean> { const score = Math.max(0, Math.min(100, update.score)); const priority = score >= 80 ? "High" : score >= 55 ? "Medium" : "Low"; const timestamp = new Date().toISOString(); const client = await sql(); if (client) { const rows = await client.query("UPDATE leads SET category=$1, priority=$2, score=$3, summary=$4, ai_reason=$5, ai_recommended_action=$6, ai_qualified_at=$7, qualification_source=$8, status='qualified' WHERE id=$9 RETURNING id", [update.category,priority,score,update.summary,update.reason,update.recommendedAction,timestamp,update.source,id]); return rows.length > 0; } return local().prepare("UPDATE leads SET category=?, priority=?, score=?, summary=?, ai_reason=?, ai_recommended_action=?, ai_qualified_at=?, qualification_source=?, status='qualified' WHERE id=?").run(update.category,priority,score,update.summary,update.reason,update.recommendedAction,timestamp,update.source,id).changes > 0; }
